### ISSUE TITLE
Project Planning Meeting Obsolete?

### ISSUE THREAD

**Issue by daniellecroxton** [learn-co-curriculum/js-spa-project-instructions#4]
The section:

> As you complete the labs leading up to the project, you should receive an email from the Section Coach about scheduling a Project Planning Meeting.
> 
> In your Project Planning Meeting, you and your coach will discuss topics like
> 
>     The basic story of your application
>     The core features you are planning to build
>     Your data models and their relationships
>     Challenges you expect to face
> 
> If you do not receive an email, and have checked your spam folder, please reach out to the Section Coach by slack or email. If reaching out by slack, please include your email address in your message.

appears to be obsolete. I did not recieve an email from the JS section coach and when I reached out to Alice about it, she said I did not have to meet with anyone before starting my project.

**Comment by Sdcrouse** [comment]
@daniellecroxton I think they changed this. I don't see that section.

**Comment by daniellecroxton** [comment]
@Sdcrouse Yes, it looks like they removed it a couple months ago, so I will close this issue. Thanks!

**Comment by Sdcrouse** [comment]
No problem!
